version: '2'
services:
    buildittest-app:
        image: buildittest
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://buildittest-postgresql:5432/builditTest
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=internal
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=internal
            - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=buildittest-elasticsearch:9300
    buildittest-postgresql:
        extends:
            file: postgresql.yml
            service: buildittest-postgresql
    buildittest-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: buildittest-elasticsearch
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak
